### PR TITLE
V2

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Phil-Friderici Having a hard time getting the installation to happen without intervention on Solaris, even though I'm providing an adminfile. Any ideas?

**Comment by ghoneycutt** [comment]
Fixes #77

**Comment by ghoneycutt** [comment]
Need to address #50 before merging. This is to remove inheritance.

**Comment by ghoneycutt** [comment]
Fixes #32

**Comment by ghoneycutt** [comment]
Fixes #42

**Comment by Phil-Friderici** [comment]
Let's try to get @nalyanyam onboard, he is our Solaris'n'Puppet specialist.
@nalyanyam hope you have some time to help :)

**Comment by nalyanyam** [comment]
Installation on which Solaris release? 10 or 11?
Solaris 10 should already be having the packages installed as part of the base OS.  Probably what's causing the puppet not to detect the installed packages is the package provider.
By default Solaris 10 uses the legacy provider "sun" while Solaris 11 uses the provider "pkg" and for Solaris 11 it's not necessary to provide adminfile as long as the repositories are properly configured.

**Comment by ghoneycutt** [comment]
Hi @nalyanyam 

The issue is not with nfs, but with the testing framework. I'm attempting to install puppet enterprise and that package is prompting for user input. The goal is that you can do `vagrant up` with the solaris10-client and solaris11-client systems without any user input, like the other platforms.

Check out theses two lines from the `vagrant/provision_solaris.sh` script.

https://github.com/ghoneycutt/puppet-module-nfs/pull/78/files#diff-efcf01caa4c8308a3dc28fd70070310bR46

https://github.com/ghoneycutt/puppet-module-nfs/pull/78/files#diff-efcf01caa4c8308a3dc28fd70070310bR50

**Comment by nalyanyam** [comment]
@ghoneycutt 
The correct command syntax is something like below:
pkgadd -n -a /var/sadm/install/admin/puppet -d  /vagrant/.puppetagents/${pkg} all

This assumes that ${pkg} is a datastream package. And the adminfile should also be ok.
The original syntax assumed a device instead of a package. Please see below notes from the man page.
Please test and let me know in case that fails


From man page:

 By default, pkgadd looks  in  the  /var/spool/pkg  directory
     when  searching  for  instances  of  a package to install or
     spool. Optionally, the source for the package  instances  to
     be installed or spooled can be specified using:

     -d device
     -d datastream pkgname,... | all

**Comment by nalyanyam** [comment]
Ref:  https://docs.oracle.com/cd/E23824_01/html/821-1462/pkgadd-1m.html

**Pull request merged**
