### PR TITLE
Update spec tests (RTM)

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Refactor the spec tests to follow the standard. Ensure all functionality is tested properly.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks @Phil-Friderici

**Comment by ghoneycutt** [comment]
Noticed the WIP, let me know when this is ready for merge.

**Comment by Phil-Friderici** [comment]
Guess it would be clever to refactor code and template to always use arrays in the other cases as well:
https://github.com/ghoneycutt/puppet-module-nfs/blob/master/templates/idmapd.conf.erb#L22-L26
https://github.com/ghoneycutt/puppet-module-nfs/blob/master/templates/idmapd.conf.erb#L41-L45
https://github.com/ghoneycutt/puppet-module-nfs/blob/master/templates/idmapd.conf.erb#L76-L81

**Comment by ghoneycutt** [comment]
Is that commit saying I should Read The Manual? :>

**Comment by ghoneycutt** [comment]
Thanks @Phil-Friderici

**Comment by Phil-Friderici** [comment]
sry 4 bd inglish, 4got the F

**Pull request merged**
