### PR TITLE
WIP - Support OmniOS 5.11

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@westbywest

**Comment by westbywest** [comment]
I tested you PR on a fork I've been keeping (since I also have some incomplete changes for improved EL7 compatibility).
https://github.com/westbywest/puppet-module-nfs/commit/c973ff0293aa4f5897520ed6732063491209a57c

I rebuilt the OmniOS vagrant guest from scratch with this PR, and it looks good.  No more unsatisfied dependencies errors as mentioned in https://github.com/ghoneycutt/puppet-module-nfs/issues/63 .

**Comment by ghoneycutt** [comment]
Awesome! Could you test with the code in this branch only and not intermixed with your changes? That would give me confirmation that this code really is good, at which point I'll write up the spec tests.

**Comment by westbywest** [comment]
Ack, nope, looks like I may have had a race condition that permitted the OmniOS vagrant guest I just tested on to start up fine.  Repeated test shows that puppet/OmniOS don't like an array being passed in the 'name' attribute for pkgutil package provider:
```
Error: Could not start Service[nfs_service]: Execution of '/usr/sbin/svcadm enable -s nfs/client nfs/nlockmgr nfs/status' returned 1: svcadm: Partial FMRI matches multiple instances
```

**Comment by westbywest** [comment]
Offering a revised PR:
https://github.com/ghoneycutt/puppet-module-nfs/pull/67

**Comment by ghoneycutt** [comment]
You can just keep pushing to this branch instead of creating new PR's each time.

**Pull request closed without merging**
