### PR TITLE
search and replace old facts by newer facts

### PR DESCRIPTION
**Pull request by lesaux**
Hello @ghoneycutt,
as you suggested, here is a PR to use the new facts.

Currently rspec is failing. I adjusted the rpcbind repo in the fixtures file to point to my fork, but it seems it's not working. (115 examples, 9 failures)

### CODE REVIEW

**Comment by visibilityspots** [comment]
+1

**Comment by ghoneycutt** [comment]
PR #47 should fix Travis. Once that is merged, could you please rebase against master and push again to pick up the changes.

**Comment by ghoneycutt** [comment]
Thanks for the patch!!

**Comment by ghoneycutt** [comment]
Thanks everyone!

Solving in v2 at PR #78

**Pull request closed without merging**
