### PR TITLE
Omnios

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Phil-Friderici https://travis-ci.org/ghoneycutt/puppet-module-nfs/jobs/98228240#L419

hash validation seems to fail at the create_resources() line. Any ideas?

**Comment by Phil-Friderici** [comment]
@ghoneycutt The positive test uses ```it { should compile }``` to verify. Therefore the hash needs to be valid to satisfy create_resources().
Nether thought of using ```it { should contain_class(subject) }``` instead. It feels incomplete to me.

**Comment by ghoneycutt** [comment]
`should contain_class` is used if the class you include then includes another class. You don't want to test all that, as that module does, but you want to ensure it is there. You are correct it shouldn't be here though. I copy/pasted from another module :\

**Comment by Phil-Friderici** [comment]
As we are dealing with variable type validations and not functionallity tests we could only test that the class doesn't fail on valid values. As side effect that would be a little bit faster. What do you think ?

**Comment by ghoneycutt** [comment]
You're proposing we use `should compile` ? Cause that's what I think should happen.

**Comment by Phil-Friderici** [comment]
I was thinking of something like this:
<pre>
    it "should not fail" do
      expect do
        subject
      end.not_to raise_error()
    end
</pre>

**Comment by ghoneycutt** [comment]
I'm updating the module to v2 in PR #78 with functional testing through Vagrant. Happy to add OmniOS, though am closing all these old tickets against the old version of NFS. Thank you for your help!

**Pull request closed without merging**
